/**
 * Dillinger's owned visual-system tokens.
 *
 * Astryx consumes the concrete light/dark pairs below. Tailwind consumes the
 * CSS variables emitted by that same Astryx theme through
 * `tailwindColorBridge`, so application utilities never duplicate palette
 * values or fall back to the retired Dillinger token names.
 */

export type ThemePair = readonly [light: string, dark: string];

export const astryxColorTokens = {
  "--color-background-body": ["#F8FAFC", "#0B1220"],
  "--color-background-surface": ["#FFFFFF", "#111827"],
  "--color-background-card": ["#FFFFFF", "#182235"],
  "--color-background-popover": ["#FFFFFF", "#182235"],
  "--color-background-muted": ["#F1F5F9", "#182235"],
  "--color-background-inverted": ["#0F172A", "#F8FAFC"],
  "--color-background-error-inverted": ["#B42318", "#FCA5A5"],

  "--color-accent": ["#4F46E5", "#818CF8"],
  "--color-accent-muted": ["#EEF2FF", "#242B55"],
  "--color-on-accent": ["#FFFFFF", "#0B1220"],
  "--color-neutral": ["#0F172A0F", "#FFFFFF14"],

  "--color-overlay": ["#0F172A80", "#020617CC"],
  "--color-overlay-hover": ["#0F172A0A", "#FFFFFF0D"],
  "--color-overlay-pressed": ["#0F172A14", "#FFFFFF17"],

  "--color-text-primary": ["#0F172A", "#F8FAFC"],
  "--color-text-secondary": ["#5D6C82", "#94A3B8"],
  "--color-text-disabled": ["#94A3B8", "#64748B"],
  "--color-text-accent": ["#4338CA", "#A5B4FC"],
  "--color-on-dark": ["#FFFFFF", "#FFFFFF"],
  "--color-on-light": ["#0F172A", "#0F172A"],

  "--color-icon-primary": ["#0F172A", "#F8FAFC"],
  "--color-icon-secondary": ["#627188", "#94A3B8"],
  "--color-icon-disabled": ["#94A3B8", "#64748B"],
  "--color-icon-accent": ["#4F46E5", "#818CF8"],

  "--color-success": ["#157F3B", "#86EFAC"],
  "--color-success-muted": ["#DCFCE7", "#123B2A"],
  "--color-on-success": ["#FFFFFF", "#0B1220"],
  "--color-warning": ["#9A6700", "#FCD34D"],
  "--color-warning-muted": ["#FEF3C7", "#422F14"],
  "--color-on-warning": ["#0F172A", "#0B1220"],
  "--color-error": ["#B42318", "#FCA5A5"],
  "--color-error-muted": ["#FEE4E2", "#491C24"],
  "--color-on-error": ["#FFFFFF", "#0B1220"],

  "--color-border": ["#E2E8F0", "#273449"],
  "--color-border-emphasized": ["#64748B", "#64748B"],
  "--color-skeleton": ["#CBD5E1", "#334155"],
  "--color-track": ["#CBD5E1", "#475569"],
  "--color-shadow": ["#0F172A1A", "#02061780"],
  "--color-tint-hover": ["#0F172A", "#FFFFFF"],
} as const satisfies Record<string, ThemePair>;

export const spacingTokens = {
  "--spacing-0": "0px",
  "--spacing-0-5": "2px",
  "--spacing-1": "4px",
  "--spacing-1-5": "6px",
  "--spacing-2": "8px",
  "--spacing-3": "12px",
  "--spacing-4": "16px",
  "--spacing-5": "20px",
  "--spacing-6": "24px",
  "--spacing-7": "28px",
  "--spacing-8": "32px",
  "--spacing-9": "36px",
  "--spacing-10": "40px",
  "--spacing-11": "44px",
  "--spacing-12": "48px",
} as const;

export const radiusTokens = {
  "--radius-none": "0px",
  "--radius-inner": "4px",
  "--radius-element": "8px",
  "--radius-container": "12px",
  "--radius-page": "20px",
  "--radius-chat": "20px",
  "--radius-full": "9999px",
} as const;

export const elevationTokens = {
  "--shadow-low": [
    "0 1px 2px #0F172A0F, 0 1px 3px #0F172A0A",
    "0 1px 2px #02061766, inset 0 0 0 1px #FFFFFF08",
  ],
  "--shadow-med": [
    "0 8px 24px #0F172A14, 0 2px 6px #0F172A0A",
    "0 12px 28px #02061780, inset 0 0 0 1px #FFFFFF0D",
  ],
  "--shadow-high": [
    "0 20px 48px #0F172A1F, 0 6px 16px #0F172A14",
    "0 24px 56px #020617B8, inset 0 0 0 1px #FFFFFF12",
  ],
  "--shadow-inset-hover": [
    "inset 0 0 0 2px #4F46E526",
    "inset 0 0 0 2px #818CF833",
  ],
  "--shadow-inset-selected": [
    "inset 0 0 0 2px #4F46E580",
    "inset 0 0 0 2px #818CF899",
  ],
  "--shadow-inset-success": [
    "inset 0 0 0 2px #157F3B66",
    "inset 0 0 0 2px #86EFAC66",
  ],
  "--shadow-inset-warning": [
    "inset 0 0 0 2px #9A670066",
    "inset 0 0 0 2px #FCD34D66",
  ],
  "--shadow-inset-error": [
    "inset 0 0 0 2px #B4231866",
    "inset 0 0 0 2px #FCA5A566",
  ],
} as const satisfies Record<string, string | ThemePair>;

/**
 * UI type scale generated by Astryx from 14px at a 1.2 ratio:
 * supporting 12px, body 14px, large 17px, h3 17px, h2 20px, h1 24px.
 * Document prose uses the same families with its larger editorial sizes in
 * globals.css.
 */
export const typographyTokens = {
  scale: { base: 14, ratio: 1.2 },
  bodyFamily: "var(--font-geist-sans)",
  codeFamily: "var(--font-geist-mono)",
} as const;

export const motionTokens = {
  fast: 120,
  medium: 240,
  slow: 480,
  ratio: 0.75,
  ease: "cubic-bezier(0.22, 1, 0.36, 1)",
} as const;

const themeVar = (name: keyof typeof astryxColorTokens) => `var(${name})`;

/** Semantic Tailwind names. These intentionally contain no compatibility aliases. */
export const tailwindColorBridge = {
  canvas: themeVar("--color-background-body"),
  surface: themeVar("--color-background-surface"),
  "surface-raised": themeVar("--color-background-card"),
  "surface-subtle": themeVar("--color-background-muted"),
  "surface-overlay": themeVar("--color-background-popover"),
  "surface-inverse": themeVar("--color-background-inverted"),
  overlay: themeVar("--color-overlay"),
  "content-strong": themeVar("--color-text-primary"),
  "content-muted": themeVar("--color-text-secondary"),
  "content-disabled": themeVar("--color-text-disabled"),
  "content-accent": themeVar("--color-text-accent"),
  "content-inverse": themeVar("--color-on-dark"),
  accent: themeVar("--color-accent"),
  "accent-soft": themeVar("--color-accent-muted"),
  "on-accent": themeVar("--color-on-accent"),
  "on-danger": themeVar("--color-on-error"),
  "on-warning": themeVar("--color-on-warning"),
  "on-success": themeVar("--color-on-success"),
  "border-subtle": themeVar("--color-border"),
  "border-control": themeVar("--color-border-emphasized"),
  "icon-strong": themeVar("--color-icon-primary"),
  "icon-muted": themeVar("--color-icon-secondary"),
  "control-track": themeVar("--color-track"),
  danger: themeVar("--color-error"),
  "danger-soft": themeVar("--color-error-muted"),
  warning: themeVar("--color-warning"),
  "warning-soft": themeVar("--color-warning-muted"),
  success: themeVar("--color-success"),
  "success-soft": themeVar("--color-success-muted"),
  "focus-ring": themeVar("--color-accent"),
} as const;
